export interface SectorDefinition {
  name: string;
  slug: string;
  description: string;
  sampleTickers: string[];
  metaDescription: string;
  keywords: string[];
  etf: string;
  color: string;
}

export const SECTORS: SectorDefinition[] = [
  {
    name: "Technology",
    slug: "technology",
    description: "Track the pulse of Silicon Valley and beyond. Our AI analyzes FAANG stocks, semiconductor moves, cloud computing trends, and AI infrastructure spending to deliver actionable tech sector insights every morning.",
    sampleTickers: ["AAPL", "MSFT", "NVDA", "GOOGL", "META"],
    metaDescription: "AI-powered daily technology sector market brief. Track FAANG stocks, semiconductors, cloud computing, and AI trends with actionable insights delivered every morning.",
    keywords: ["tech stocks", "FAANG analysis", "technology sector brief", "AI stocks", "semiconductor analysis"],
    etf: "XLK",
    color: "indigo",
  },
  {
    name: "Healthcare",
    slug: "healthcare",
    description: "Stay ahead of biotech catalysts, pharma pipelines, and healthcare policy shifts. Our AI tracks FDA approvals, clinical trial results, and hospital sector trends to surface opportunities before the crowd.",
    sampleTickers: ["UNH", "JNJ", "LLY", "PFE", "ABBV"],
    metaDescription: "AI-powered daily healthcare sector market brief. Track biotech catalysts, pharma pipelines, FDA approvals, and healthcare policy with morning insights.",
    keywords: ["healthcare stocks", "biotech analysis", "pharma stocks", "FDA approvals", "healthcare brief"],
    etf: "XLV",
    color: "emerald",
  },
  {
    name: "Energy",
    slug: "energy",
    description: "Navigate the energy transition with clarity. From crude oil dynamics and natural gas volatility to solar, wind, and nuclear power trends. Our AI covers both traditional and clean energy sectors.",
    sampleTickers: ["XOM", "CVX", "COP", "NEE", "ENPH"],
    metaDescription: "AI-powered daily energy sector market brief. Track oil prices, natural gas, renewables, and energy stocks with actionable morning analysis.",
    keywords: ["energy stocks", "oil price analysis", "renewable energy stocks", "natural gas", "energy brief"],
    etf: "XLE",
    color: "amber",
  },
  {
    name: "Finance",
    slug: "finance",
    description: "Monitor the financial sector that moves markets. From bank earnings and interest rate sensitivity to fintech disruption and insurance trends. Our AI connects the dots between Fed policy and financial stock performance.",
    sampleTickers: ["JPM", "BAC", "GS", "V", "BRK-B"],
    metaDescription: "AI-powered daily financial sector market brief. Track bank stocks, interest rates, fintech trends, and financial services with morning analysis.",
    keywords: ["financial stocks", "bank analysis", "interest rate impact", "fintech", "financial brief"],
    etf: "XLF",
    color: "blue",
  },
  {
    name: "Consumer",
    slug: "consumer",
    description: "Understand what consumers are buying and why. From retail earnings and e-commerce trends to consumer confidence shifts and brand performance. Our AI tracks both discretionary and staples sectors.",
    sampleTickers: ["AMZN", "TSLA", "HD", "PG", "KO"],
    metaDescription: "AI-powered daily consumer sector market brief. Track retail, e-commerce, consumer confidence, and brand performance with morning analysis.",
    keywords: ["consumer stocks", "retail analysis", "e-commerce stocks", "consumer spending", "consumer brief"],
    etf: "XLY",
    color: "purple",
  },
  {
    name: "Industrial",
    slug: "industrial",
    description: "Track the backbone of the economy. From aerospace & defense to transportation, construction, and manufacturing. Our AI monitors supply chain dynamics, PMI data, and infrastructure spending trends.",
    sampleTickers: ["CAT", "BA", "UNP", "HON", "GE"],
    metaDescription: "AI-powered daily industrial sector market brief. Track manufacturing, aerospace, transportation, and infrastructure stocks with morning analysis.",
    keywords: ["industrial stocks", "manufacturing analysis", "aerospace stocks", "infrastructure", "industrial brief"],
    etf: "XLI",
    color: "slate",
  },
  {
    name: "Real Estate",
    slug: "real-estate",
    description: "Navigate the real estate market with data-driven insights. From REITs and commercial property trends to mortgage rates and housing data. Our AI analyzes how interest rates and economic shifts impact real estate investments.",
    sampleTickers: ["PLD", "AMT", "EQIX", "SPG", "O"],
    metaDescription: "AI-powered daily real estate sector market brief. Track REITs, commercial property, mortgage rates, and housing data with morning analysis.",
    keywords: ["real estate stocks", "REIT analysis", "mortgage rates", "commercial real estate", "real estate brief"],
    etf: "XLRE",
    color: "teal",
  },
  {
    name: "Crypto",
    slug: "crypto",
    description: "Cut through the noise of crypto markets. From Bitcoin and Ethereum price action to DeFi protocol metrics, regulatory developments, and institutional adoption trends. Our AI delivers signal, not speculation.",
    sampleTickers: ["BTC", "ETH", "SOL", "COIN", "MSTR"],
    metaDescription: "AI-powered daily crypto market brief. Track Bitcoin, Ethereum, DeFi trends, and crypto regulation with actionable morning analysis.",
    keywords: ["crypto analysis", "Bitcoin brief", "Ethereum analysis", "DeFi trends", "crypto market brief"],
    etf: "BITO",
    color: "orange",
  },
  {
    name: "Commodities",
    slug: "commodities",
    description: "Stay informed on commodity markets that drive global trade. From precious metals and agriculture to industrial metals and soft commodities. Our AI tracks supply-demand dynamics, weather impacts, and geopolitical risks.",
    sampleTickers: ["GLD", "SLV", "USO", "DBA", "CPER"],
    metaDescription: "AI-powered daily commodities market brief. Track gold, oil, agriculture, and industrial metals with actionable morning analysis.",
    keywords: ["commodities analysis", "gold price brief", "oil market", "agriculture stocks", "commodities brief"],
    etf: "DJP",
    color: "yellow",
  },
  {
    name: "Emerging Markets",
    slug: "emerging-markets",
    description: "Access growth opportunities in developing economies. From China and India tech plays to Latin American consumer growth and Southeast Asian manufacturing. Our AI covers the sectors driving emerging market outperformance.",
    sampleTickers: ["EEM", "FXI", "INDA", "EWZ", "VWO"],
    metaDescription: "AI-powered daily emerging markets brief. Track China, India, Latin America, and developing economy stocks with morning analysis.",
    keywords: ["emerging markets", "China stocks", "India stocks", "emerging market brief", "developing economies"],
    etf: "EEM",
    color: "rose",
  },
  {
    name: "Utilities",
    slug: "utilities",
    description: "Track the defensive sector with growth potential. From traditional power utilities to data center energy demand and nuclear renaissance. Our AI analyzes dividend yields, regulatory changes, and the electrification megatrend.",
    sampleTickers: ["NEE", "DUK", "SO", "D", "AEP"],
    metaDescription: "AI-powered daily utilities sector market brief. Track power utilities, dividends, data center energy demand, and nuclear trends with morning analysis.",
    keywords: ["utility stocks", "dividend stocks", "nuclear energy", "data center power", "utilities brief"],
    etf: "XLU",
    color: "cyan",
  },
  {
    name: "Materials",
    slug: "materials",
    description: "Monitor the raw materials powering the economy. From lithium and copper for EV batteries to steel, chemicals, and packaging. Our AI tracks commodity cycles, supply constraints, and materials sector catalysts.",
    sampleTickers: ["LIN", "APD", "FCX", "NEM", "ECL"],
    metaDescription: "AI-powered daily materials sector market brief. Track mining stocks, chemicals, lithium, copper, and materials with morning analysis.",
    keywords: ["materials stocks", "mining analysis", "lithium stocks", "copper stocks", "materials brief"],
    etf: "XLB",
    color: "stone",
  },
  {
    name: "Communication Services",
    slug: "communication-services",
    description: "Track the intersection of media, entertainment, and telecom. From streaming wars and social media monetization to 5G deployment and digital advertising trends. Our AI covers the companies shaping how we connect.",
    sampleTickers: ["META", "GOOGL", "DIS", "NFLX", "T"],
    metaDescription: "AI-powered daily communication services market brief. Track social media, streaming, telecom, and digital advertising with morning analysis.",
    keywords: ["communication stocks", "social media stocks", "streaming analysis", "telecom stocks", "media brief"],
    etf: "XLC",
    color: "violet",
  },
  {
    name: "Small Caps",
    slug: "small-caps",
    description: "Discover opportunities in the small-cap universe. From high-growth startups to undervalued gems. Our AI screens Russell 2000 trends, identifies relative strength, and flags small-cap stocks with institutional momentum.",
    sampleTickers: ["IWM", "SMCI", "AFRM", "CELH", "DUOL"],
    metaDescription: "AI-powered daily small-cap market brief. Track Russell 2000 trends, growth stocks, and small-cap opportunities with morning analysis.",
    keywords: ["small cap stocks", "Russell 2000", "growth stocks", "small cap brief", "micro cap analysis"],
    etf: "IWM",
    color: "pink",
  },
  {
    name: "Dividends & Income",
    slug: "dividends-income",
    description: "Build wealth with income-generating investments. Our AI tracks dividend aristocrats, high-yield opportunities, ex-dividend dates, and payout ratio sustainability to help you make smarter income investing decisions.",
    sampleTickers: ["VYM", "SCHD", "O", "JNJ", "PG"],
    metaDescription: "AI-powered daily dividend and income investing brief. Track dividend aristocrats, high-yield stocks, and income strategies with morning analysis.",
    keywords: ["dividend stocks", "income investing", "dividend aristocrats", "high yield stocks", "dividend brief"],
    etf: "VYM",
    color: "green",
  },
  {
    name: "AI & Machine Learning",
    slug: "ai-machine-learning",
    description: "Stay at the forefront of the AI revolution. From GPU makers and cloud AI platforms to enterprise AI adoption and autonomous systems. Our AI tracks the companies building and deploying artificial intelligence.",
    sampleTickers: ["NVDA", "MSFT", "GOOGL", "AMD", "PLTR"],
    metaDescription: "AI-powered daily AI and machine learning sector brief. Track NVIDIA, AI infrastructure, enterprise AI, and ML trends with morning analysis.",
    keywords: ["AI stocks", "machine learning stocks", "NVIDIA analysis", "artificial intelligence investing", "AI brief"],
    etf: "BOTZ",
    color: "fuchsia",
  },
  {
    name: "Defense & Aerospace",
    slug: "defense-aerospace",
    description: "Track defense spending, space exploration, and aerospace innovation. From military contracts and geopolitical tensions to commercial aviation recovery and satellite technology. Our AI covers the full spectrum.",
    sampleTickers: ["LMT", "RTX", "NOC", "BA", "GD"],
    metaDescription: "AI-powered daily defense and aerospace sector brief. Track military contracts, space tech, and aviation stocks with morning analysis.",
    keywords: ["defense stocks", "aerospace stocks", "military spending", "space stocks", "defense brief"],
    etf: "ITA",
    color: "neutral",
  },
  {
    name: "Clean Energy",
    slug: "clean-energy",
    description: "Navigate the green energy transition. From solar and wind to hydrogen, EVs, and battery storage. Our AI tracks policy incentives, technology breakthroughs, and the companies leading the shift to sustainable energy.",
    sampleTickers: ["ENPH", "SEDG", "FSLR", "PLUG", "RIVN"],
    metaDescription: "AI-powered daily clean energy sector brief. Track solar, wind, EV, hydrogen, and green energy stocks with morning analysis.",
    keywords: ["clean energy stocks", "solar stocks", "EV stocks", "renewable energy", "green energy brief"],
    etf: "ICLN",
    color: "lime",
  },
  {
    name: "Biotech",
    slug: "biotech",
    description: "Navigate high-risk, high-reward biotech investing. From FDA catalysts and clinical trial data to M&A activity and gene therapy breakthroughs. Our AI flags the events that move biotech stocks dramatically.",
    sampleTickers: ["AMGN", "GILD", "REGN", "VRTX", "MRNA"],
    metaDescription: "AI-powered daily biotech sector brief. Track FDA catalysts, clinical trials, gene therapy, and biotech M&A with morning analysis.",
    keywords: ["biotech stocks", "FDA catalysts", "clinical trials", "gene therapy", "biotech brief"],
    etf: "XBI",
    color: "sky",
  },
  {
    name: "Global Macro",
    slug: "global-macro",
    description: "See the big picture of global markets. From central bank policies and currency moves to trade flows and geopolitical risk. Our AI synthesizes macro data to help you understand the forces moving all asset classes.",
    sampleTickers: ["SPY", "TLT", "UUP", "FXE", "GLD"],
    metaDescription: "AI-powered daily global macro market brief. Track central bank policy, currencies, bonds, and geopolitical risk with morning analysis.",
    keywords: ["global macro", "central bank policy", "bond market", "currency analysis", "macro brief"],
    etf: "ACWI",
    color: "zinc",
  },
];

export function getSectorBySlug(slug: string): SectorDefinition | undefined {
  return SECTORS.find((s) => s.slug === slug);
}

export function getAllSectorSlugs(): string[] {
  return SECTORS.map((s) => s.slug);
}
